export const products = [
  // Detox (8)
  {
    id: 1,
    name: 'Apple Juice Cleanse',
    price: 499,
    short: 'Fresh apple & green goodness',
    long: 'Pure cold-pressed apple juice with a refreshing cleanse.',
    image: '/assets/products/apple.png',
    category: 'Detox',
    flavor: 'Apple',
    flavorColor: '#8DB600',
    fruitIngredients: ['Apple'],
    sizes: [
      { size: '250ml', price: 299, calories: 120, protein: '1g', carbs: '28g', sugar: '24g', vitaminC: '40%', servingSize: '250ml' },
      { size: '500ml', price: 499, calories: 240, protein: '2g', carbs: '56g', sugar: '48g', vitaminC: '80%', servingSize: '500ml' },
      { size: '1L', price: 899, calories: 480, protein: '4g', carbs: '112g', sugar: '96g', vitaminC: '160%', servingSize: '1000ml' },
    ],
  },
  {
    id: 2,
    name: 'Kiwi Fruit Kick',
    price: 549,
    short: 'Tangy kiwi & citrus burst',
    long: 'Energizing kiwifruit blend with a zesty citrus kick.',
    image: '/assets/products/kiwi.png',
    category: 'Detox',
    flavor: 'Kiwi',
    flavorColor: '#7CB342',
    fruitIngredients: ['Kiwi', 'Orange', 'Lemon'],
    sizes: [
      { size: '250ml', price: 329, calories: 110, protein: '2g', carbs: '26g', sugar: '22g', vitaminC: '80%', servingSize: '250ml' },
      { size: '500ml', price: 549, calories: 220, protein: '4g', carbs: '52g', sugar: '44g', vitaminC: '160%', servingSize: '500ml' },
      { size: '1L', price: 999, calories: 440, protein: '8g', carbs: '104g', sugar: '88g', vitaminC: '320%', servingSize: '1000ml' },
    ],
  },
  {
    id: 3,
    name: 'Orange Sunrise Boost',
    price: 519,
    short: 'Fresh orange & vitamin C',
    long: 'Bright orange juice packed with natural vitamin C.',
    image: '/assets/products/orange.png',
    category: 'Detox',
    flavor: 'Orange',
    flavorColor: '#FF8C00',
    fruitIngredients: ['Orange'],
    sizes: [
      { size: '250ml', price: 319, calories: 115, protein: '2g', carbs: '27g', sugar: '21g', vitaminC: '100%', servingSize: '250ml' },
      { size: '500ml', price: 519, calories: 230, protein: '4g', carbs: '54g', sugar: '42g', vitaminC: '200%', servingSize: '500ml' },
      { size: '1L', price: 949, calories: 460, protein: '8g', carbs: '108g', sugar: '84g', vitaminC: '400%', servingSize: '1000ml' },
    ],
  },
  {
    id: 4,
    name: 'Watermelon Wave',
    price: 449,
    short: 'Sweet watermelon refresh',
    long: 'Hydrating watermelon juice with a cool, sweet finish.',
    image: '/assets/products/watermelon.png',
    category: 'Detox',
    flavor: 'Watermelon',
    flavorColor: '#FF6B9D',
    fruitIngredients: ['Watermelon', 'Lime'],
    sizes: [
      { size: '250ml', price: 269, calories: 95, protein: '1g', carbs: '22g', sugar: '20g', vitaminC: '25%', servingSize: '250ml' },
      { size: '500ml', price: 449, calories: 190, protein: '2g', carbs: '44g', sugar: '40g', vitaminC: '50%', servingSize: '500ml' },
      { size: '1L', price: 799, calories: 380, protein: '4g', carbs: '88g', sugar: '80g', vitaminC: '100%', servingSize: '1000ml' },
    ],
  },
  {
    id: 5,
    name: 'Grape Glow Elixir',
    price: 459,
    short: 'Red grape & antioxidants',
    long: 'Rich red grape juice loaded with antioxidants.',
    image: '/assets/products/grape.png',
    category: 'Detox',
    flavor: 'Grape',
    flavorColor: '#9C27B0',
    fruitIngredients: ['Grape'],
    sizes: [
      { size: '250ml', price: 249, calories: 105, protein: '1g', carbs: '26g', sugar: '23g', vitaminC: '30%', servingSize: '250ml' },
      { size: '500ml', price: 459, calories: 210, protein: '2g', carbs: '52g', sugar: '46g', vitaminC: '60%', servingSize: '500ml' },
      { size: '1L', price: 849, calories: 420, protein: '4g', carbs: '104g', sugar: '92g', vitaminC: '120%', servingSize: '1L' },
    ],
  },
  {
    id: 6,
    name: 'Pineapple Paradise',
    price: 469,
    short: 'Tropical pineapple delight',
    long: 'Sweet tropical pineapple juice with island vibes.',
    image: '/assets/products/pineapple.png',
    category: 'Detox',
    flavor: 'Pineapple',
    flavorColor: '#FFD700',
    fruitIngredients: ['Pineapple', 'Coconut'],
    sizes: [
      { size: '250ml', price: 259, calories: 110, protein: '1g', carbs: '27g', sugar: '22g', vitaminC: '45%', servingSize: '250ml' },
      { size: '500ml', price: 469, calories: 220, protein: '2g', carbs: '54g', sugar: '44g', vitaminC: '90%', servingSize: '500ml' },
      { size: '1L', price: 859, calories: 440, protein: '4g', carbs: '108g', sugar: '88g', vitaminC: '180%', servingSize: '1L' },
    ],
  },
  {
    id: 7,
    name: 'Mango Bliss',
    price: 509,
    short: 'Ripe mango perfection',
    long: 'Smooth, velvety mango juice with tropical sweetness.',
    image: '/assets/products/mango.png',
    category: 'Detox',
    flavor: 'Mango',
    flavorColor: '#FFA726',
    fruitIngredients: ['Mango'],
    sizes: [
      { size: '250ml', price: 279, calories: 125, protein: '2g', carbs: '30g', sugar: '27g', vitaminC: '35%', servingSize: '250ml' },
      { size: '500ml', price: 509, calories: 250, protein: '4g', carbs: '60g', sugar: '54g', vitaminC: '70%', servingSize: '500ml' },
      { size: '1L', price: 929, calories: 500, protein: '8g', carbs: '120g', sugar: '108g', vitaminC: '140%', servingSize: '1L' },
    ],
  },
  {
    id: 8,
    name: 'Strawberry Fields',
    price: 499,
    short: 'Fresh strawberry crush',
    long: 'Sweet, fragrant strawberry juice with berry richness.',
    image: '/assets/products/strawberry.png',
    category: 'Detox',
    flavor: 'Strawberry',
    flavorColor: '#E91E63',
    fruitIngredients: ['Strawberry'],
    sizes: [
      { size: '250ml', price: 269, calories: 115, protein: '1g', carbs: '28g', sugar: '24g', vitaminC: '50%', servingSize: '250ml' },
      { size: '500ml', price: 499, calories: 230, protein: '2g', carbs: '56g', sugar: '48g', vitaminC: '100%', servingSize: '500ml' },
      { size: '1L', price: 899, calories: 460, protein: '4g', carbs: '112g', sugar: '96g', vitaminC: '200%', servingSize: '1L' },
    ],
  },

  // Smoothies (8)
  {
    id: 9,
    name: 'Blueberry Dream',
    price: 539,
    short: 'Blueberry & Greek yogurt',
    long: 'Creamy blueberry smoothie with protein-rich Greek yogurt.',
    image: '/assets/products/blueberry.png',
    category: 'Smoothies',
    flavor: 'Blueberry',
    flavorColor: '#5C6BC0',
    fruitIngredients: ['Blueberry', 'Banana'],
    sizes: [
      { size: '250ml', price: 299, calories: 140, protein: '4g', carbs: '26g', sugar: '20g', vitaminC: '20%', servingSize: '250ml' },
      { size: '500ml', price: 539, calories: 280, protein: '8g', carbs: '52g', sugar: '40g', vitaminC: '40%', servingSize: '500ml' },
      { size: '1L', price: 979, calories: 560, protein: '16g', carbs: '104g', sugar: '80g', vitaminC: '80%', servingSize: '1L' },
    ],
  },
  {
    id: 10,
    name: 'Banana Split Smoothie',
    price: 579,
    short: 'Banana, honey & almond',
    long: 'Classic banana smoothie with honey and almond milk.',
    image: '/assets/products/banana.png',
    category: 'Smoothies',
    flavor: 'Banana',
    flavorColor: '#FFE082',
    fruitIngredients: ['Banana', 'Strawberry'],
    sizes: [
      { size: '250ml', price: 319, calories: 155, protein: '3g', carbs: '32g', sugar: '24g', vitaminC: '15%', servingSize: '250ml' },
      { size: '500ml', price: 579, calories: 310, protein: '6g', carbs: '64g', sugar: '48g', vitaminC: '30%', servingSize: '500ml' },
      { size: '1L', price: 1049, calories: 620, protein: '12g', carbs: '128g', sugar: '96g', vitaminC: '60%', servingSize: '1L' },
    ],
  },
  {
    id: 11,
    name: 'Peach Perfection',
    price: 659,
    short: 'Peach, vanilla & oat milk',
    long: 'Velvety peach smoothie with vanilla and creamy oats.',
    image: '/assets/products/peach.png',
    category: 'Smoothies',
    flavor: 'Peach',
    flavorColor: '#FFAB91',
    fruitIngredients: ['Peach'],
    sizes: [
      { size: '250ml', price: 359, calories: 145, protein: '4g', carbs: '28g', sugar: '22g', vitaminC: '25%', servingSize: '250ml' },
      { size: '500ml', price: 659, calories: 290, protein: '8g', carbs: '56g', sugar: '44g', vitaminC: '50%', servingSize: '500ml' },
      { size: '1L', price: 1199, calories: 580, protein: '16g', carbs: '112g', sugar: '88g', vitaminC: '100%', servingSize: '1L' },
    ],
  },
  {
    id: 12,
    name: 'Cherry Charm',
    price: 579,
    short: 'Sweet cherry & yogurt',
    long: 'Rich cherry smoothie with a tangy yogurt twist.',
    image: '/assets/products/product-12.png',
    category: 'Smoothies',
    flavor: 'Cherry',
    flavorColor: '#D32F2F',
    fruitIngredients: ['Cherry', 'Banana'],
    sizes: [
      { size: '250ml', price: 319, calories: 135, protein: '4g', carbs: '26g', sugar: '21g', vitaminC: '30%', servingSize: '250ml' },
      { size: '500ml', price: 579, calories: 270, protein: '8g', carbs: '52g', sugar: '42g', vitaminC: '60%', servingSize: '500ml' },
      { size: '1L', price: 1049, calories: 540, protein: '16g', carbs: '104g', sugar: '84g', vitaminC: '120%', servingSize: '1L' },
    ],
  },
  {
    id: 13,
    name: 'Papaya Power Blend',
    price: 559,
    short: 'Papaya, lime & coconut',
    long: 'Tropical papaya smoothie with lime and coconut cream.',
    image: '/assets/products/product-13.png',
    category: 'Smoothies',
    flavor: 'Papaya',
    flavorColor: '#FF7043',
    fruitIngredients: ['Papaya', 'Lime', 'Coconut'],
    sizes: [
      { size: '250ml', price: 309, calories: 150, protein: '3g', carbs: '30g', sugar: '25g', vitaminC: '60%', servingSize: '250ml' },
      { size: '500ml', price: 559, calories: 300, protein: '6g', carbs: '60g', sugar: '50g', vitaminC: '120%', servingSize: '500ml' },
      { size: '1L', price: 1019, calories: 600, protein: '12g', carbs: '120g', sugar: '100g', vitaminC: '240%', servingSize: '1L' },
    ],
  },
  {
    id: 14,
    name: 'Guava Goodness',
    price: 549,
    short: 'Pink guava & passion fruit',
    long: 'Exotic guava smoothie with passion fruit tang.',
    image: '/assets/products/product-14.png',
    category: 'Smoothies',
    flavor: 'Guava',
    flavorColor: '#F8BBD0',
    fruitIngredients: ['Guava'],
    sizes: [
      { size: '250ml', price: 299, calories: 145, protein: '3g', carbs: '28g', sugar: '23g', vitaminC: '80%', servingSize: '250ml' },
      { size: '500ml', price: 549, calories: 290, protein: '6g', carbs: '56g', sugar: '46g', vitaminC: '160%', servingSize: '500ml' },
      { size: '1L', price: 999, calories: 580, protein: '12g', carbs: '112g', sugar: '92g', vitaminC: '320%', servingSize: '1L' },
    ],
  },
  {
    id: 15,
    name: 'Lychee Love',
    price: 559,
    short: 'Lychee & rose water',
    long: 'Delicate lychee smoothie with a hint of rose.',
    image: '/assets/products/product-15.png',
    category: 'Smoothies',
    flavor: 'Lychee',
    flavorColor: '#FCE4EC',
    fruitIngredients: ['Lychee'],
    sizes: [
      { size: '250ml', price: 309, calories: 130, protein: '2g', carbs: '30g', sugar: '26g', vitaminC: '35%', servingSize: '250ml' },
      { size: '500ml', price: 559, calories: 260, protein: '4g', carbs: '60g', sugar: '52g', vitaminC: '70%', servingSize: '500ml' },
      { size: '1L', price: 1019, calories: 520, protein: '8g', carbs: '120g', sugar: '104g', vitaminC: '140%', servingSize: '1L' },
    ],
  },
  {
    id: 16,
    name: 'Dragon Fruit Delight',
    price: 569,
    short: 'Dragon fruit & chia seeds',
    long: 'Vibrant dragon fruit smoothie with omega-rich chia.',
    image: '/assets/products/product-16.png',
    category: 'Smoothies',
    flavor: 'Dragon Fruit',
    flavorColor: '#EC407A',
    fruitIngredients: ['Dragon Fruit', 'Banana'],
    sizes: [
      { size: '250ml', price: 319, calories: 135, protein: '4g', carbs: '26g', sugar: '20g', vitaminC: '40%', servingSize: '250ml' },
      { size: '500ml', price: 569, calories: 270, protein: '8g', carbs: '52g', sugar: '40g', vitaminC: '80%', servingSize: '500ml' },
      { size: '1L', price: 1039, calories: 540, protein: '16g', carbs: '104g', sugar: '80g', vitaminC: '160%', servingSize: '1L' },
    ],
  },

  // Protein (8)
  {
    id: 17,
    name: 'Raspberry Protein Punch',
    price: 619,
    short: 'Raspberry, whey & almond',
    long: 'Tart raspberry with smooth whey protein and almond milk.',
    image: '/assets/products/product-17.png',
    category: 'Protein',
    flavor: 'Raspberry',
    flavorColor: '#C2185B',
    fruitIngredients: ['Raspberry'],
    sizes: [
      { size: '250ml', price: 339, calories: 165, protein: '10g', carbs: '20g', sugar: '15g', vitaminC: '35%', servingSize: '250ml' },
      { size: '500ml', price: 619, calories: 330, protein: '20g', carbs: '40g', sugar: '30g', vitaminC: '70%', servingSize: '500ml' },
      { size: '1L', price: 1129, calories: 660, protein: '40g', carbs: '80g', sugar: '60g', vitaminC: '140%', servingSize: '1L' },
    ],
  },
  {
    id: 18,
    name: 'Blackberry Muscle Mix',
    price: 629,
    short: 'Blackberry, oats & protein',
    long: 'Bold blackberry with hearty oats and whey protein.',
    image: '/assets/products/product-18.png',
    category: 'Protein',
    flavor: 'Blackberry',
    flavorColor: '#4A148C',
    fruitIngredients: ['Blackberry', 'Banana'],
    sizes: [
      { size: '250ml', price: 349, calories: 170, protein: '11g', carbs: '22g', sugar: '14g', vitaminC: '25%', servingSize: '250ml' },
      { size: '500ml', price: 629, calories: 340, protein: '22g', carbs: '44g', sugar: '28g', vitaminC: '50%', servingSize: '500ml' },
      { size: '1L', price: 1149, calories: 680, protein: '44g', carbs: '88g', sugar: '56g', vitaminC: '100%', servingSize: '1L' },
    ],
  },
  {
    id: 19,
    name: 'Apricot Energy Shake',
    price: 639,
    short: 'Apricot, banana & whey',
    long: 'Sweet apricot protein shake with banana creaminess.',
    image: '/assets/products/product-19.png',
    category: 'Protein',
    flavor: 'Apricot',
    flavorColor: '#FFCC80',
    fruitIngredients: ['Apricot', 'Banana'],
    sizes: [
      { size: '250ml', price: 359, calories: 175, protein: '12g', carbs: '24g', sugar: '18g', vitaminC: '30%', servingSize: '250ml' },
      { size: '500ml', price: 639, calories: 350, protein: '24g', carbs: '48g', sugar: '36g', vitaminC: '60%', servingSize: '500ml' },
      { size: '1L', price: 1169, calories: 700, protein: '48g', carbs: '96g', sugar: '72g', vitaminC: '120%', servingSize: '1L' },
    ],
  },
  {
    id: 20,
    name: 'Pomegranate Power',
    price: 649,
    short: 'Pomegranate, berries & protein',
    long: 'Antioxidant-rich pomegranate with mixed berries and whey.',
    image: '/assets/products/product-20.png',
    category: 'Protein',
    flavor: 'Pomegranate',
    flavorColor: '#AD1457',
    fruitIngredients: ['Pomegranate', 'Blueberry', 'Raspberry'],
    sizes: [
      { size: '250ml', price: 359, calories: 180, protein: '13g', carbs: '22g', sugar: '17g', vitaminC: '40%', servingSize: '250ml' },
      { size: '500ml', price: 649, calories: 360, protein: '26g', carbs: '44g', sugar: '34g', vitaminC: '80%', servingSize: '500ml' },
      { size: '1L', price: 1189, calories: 720, protein: '52g', carbs: '88g', sugar: '68g', vitaminC: '160%', servingSize: '1L' },
    ],
  },
  {
    id: 21,
    name: 'Coconut Protein Paradise',
    price: 609,
    short: 'Coconut milk, pineapple & whey',
    long: 'Tropical coconut protein with sweet pineapple chunks.',
    image: '/assets/products/product-21.png',
    category: 'Protein',
    flavor: 'Coconut',
    flavorColor: '#FFFFFF',
    fruitIngredients: ['Coconut', 'Pineapple'],
    sizes: [
      { size: '250ml', price: 339, calories: 160, protein: '10g', carbs: '20g', sugar: '16g', vitaminC: '35%', servingSize: '250ml' },
      { size: '500ml', price: 609, calories: 320, protein: '20g', carbs: '40g', sugar: '32g', vitaminC: '70%', servingSize: '500ml' },
      { size: '1L', price: 1109, calories: 640, protein: '40g', carbs: '80g', sugar: '64g', vitaminC: '140%', servingSize: '1L' },
    ],
  },
  {
    id: 22,
    name: 'Fig Fitness Fuel',
    price: 639,
    short: 'Fig, date & pea protein',
    long: 'Natural fig sweetness with dates and plant protein.',
    image: '/assets/products/product-22.png',
    category: 'Protein',
    flavor: 'Fig',
    flavorColor: '#8D6E63',
    fruitIngredients: ['Fig'],
    sizes: [
      { size: '250ml', price: 349, calories: 170, protein: '11g', carbs: '26g', sugar: '20g', vitaminC: '20%', servingSize: '250ml' },
      { size: '500ml', price: 639, calories: 340, protein: '22g', carbs: '52g', sugar: '40g', vitaminC: '40%', servingSize: '500ml' },
      { size: '1L', price: 1169, calories: 680, protein: '44g', carbs: '104g', sugar: '80g', vitaminC: '80%', servingSize: '1L' },
    ],
  },
  {
    id: 23,
    name: 'Plum Performance',
    price: 629,
    short: 'Plum, vanilla & whey',
    long: 'Juicy plum protein shake with smooth vanilla notes.',
    image: '/assets/products/product-23.png',
    category: 'Protein',
    flavor: 'Plum',
    flavorColor: '#6A1B9A',
    fruitIngredients: ['Plum'],
    sizes: [
      { size: '250ml', price: 349, calories: 165, protein: '11g', carbs: '22g', sugar: '16g', vitaminC: '25%', servingSize: '250ml' },
      { size: '500ml', price: 629, calories: 330, protein: '22g', carbs: '44g', sugar: '32g', vitaminC: '50%', servingSize: '500ml' },
      { size: '1L', price: 1149, calories: 660, protein: '44g', carbs: '88g', sugar: '64g', vitaminC: '100%', servingSize: '1L' },
    ],
  },
  {
    id: 24,
    name: 'Avocado Green Protein',
    price: 639,
    short: 'Avocado, spinach & hemp protein',
    long: 'Creamy avocado with greens and plant-based hemp protein.',
    image: '/assets/products/product-24.png',
    category: 'Protein',
    flavor: 'Avocado',
    flavorColor: '#689F38',
    fruitIngredients: ['Avocado', 'Banana'],
    sizes: [
      { size: '250ml', price: 359, calories: 175, protein: '12g', carbs: '18g', sugar: '8g', vitaminC: '30%', servingSize: '250ml' },
      { size: '500ml', price: 639, calories: 350, protein: '24g', carbs: '36g', sugar: '16g', vitaminC: '60%', servingSize: '500ml' },
      { size: '1L', price: 1169, calories: 700, protein: '48g', carbs: '72g', sugar: '32g', vitaminC: '120%', servingSize: '1L' },
    ],
  },

  // Wellness (8)
  {
    id: 25,
    name: 'Grapefruit Glow',
    price: 449,
    short: 'Pink grapefruit & honey',
    long: 'Tangy pink grapefruit with a touch of natural honey.',
    image: '/assets/products/product-25.png',
    category: 'Wellness',
    flavor: 'Grapefruit',
    flavorColor: '#FF6F61',
    fruitIngredients: ['Grapefruit'],
    sizes: [
      { size: '250ml', price: 249, calories: 95, protein: '1g', carbs: '22g', sugar: '18g', vitaminC: '70%', servingSize: '250ml' },
      { size: '500ml', price: 449, calories: 190, protein: '2g', carbs: '44g', sugar: '36g', vitaminC: '140%', servingSize: '500ml' },
      { size: '1L', price: 829, calories: 380, protein: '4g', carbs: '88g', sugar: '72g', vitaminC: '280%', servingSize: '1L' },
    ],
  },
  {
    id: 26,
    name: 'Lemon Lime Vitality',
    price: 479,
    short: 'Lemon, lime & mint',
    long: 'Refreshing citrus duo with cooling mint leaves.',
    image: '/assets/products/product-26.png',
    category: 'Wellness',
    flavor: 'Lemon Lime',
    flavorColor: '#C5E1A5',
    fruitIngredients: ['Lemon', 'Lime'],
    sizes: [
      { size: '250ml', price: 259, calories: 105, protein: '1g', carbs: '26g', sugar: '20g', vitaminC: '90%', servingSize: '250ml' },
      { size: '500ml', price: 479, calories: 210, protein: '2g', carbs: '52g', sugar: '40g', vitaminC: '180%', servingSize: '500ml' },
      { size: '1L', price: 879, calories: 420, protein: '4g', carbs: '104g', sugar: '80g', vitaminC: '360%', servingSize: '1L' },
    ],
  },
  {
    id: 27,
    name: 'Cranberry Cleanse',
    price: 399,
    short: 'Cranberry & hibiscus',
    long: 'Tart cranberry juice with floral hibiscus notes.',
    image: '/assets/products/product-27.png',
    category: 'Wellness',
    flavor: 'Cranberry',
    flavorColor: '#D32F2F',
    fruitIngredients: ['Cranberry'],
    sizes: [
      { size: '250ml', price: 229, calories: 85, protein: '1g', carbs: '20g', sugar: '16g', vitaminC: '45%', servingSize: '250ml' },
      { size: '500ml', price: 399, calories: 170, protein: '2g', carbs: '40g', sugar: '32g', vitaminC: '90%', servingSize: '500ml' },
      { size: '1L', price: 749, calories: 340, protein: '4g', carbs: '80g', sugar: '64g', vitaminC: '180%', servingSize: '1L' },
    ],
  },
  {
    id: 28,
    name: 'Acai Berry Immunity',
    price: 489,
    short: 'Acai, blueberry & elderberry',
    long: 'Superfood acai blend with immune-boosting elderberry.',
    image: '/assets/products/product-28.png',
    category: 'Wellness',
    flavor: 'Acai',
    flavorColor: '#512DA8',
    fruitIngredients: ['Acai', 'Blueberry'],
    sizes: [
      { size: '250ml', price: 269, calories: 125, protein: '2g', carbs: '28g', sugar: '22g', vitaminC: '55%', servingSize: '250ml' },
      { size: '500ml', price: 489, calories: 250, protein: '4g', carbs: '56g', sugar: '44g', vitaminC: '110%', servingSize: '500ml' },
      { size: '1L', price: 899, calories: 500, protein: '8g', carbs: '112g', sugar: '88g', vitaminC: '220%', servingSize: '1L' },
    ],
  },
  {
    id: 29,
    name: 'Passion Fruit Zen',
    price: 509,
    short: 'Passion fruit & chamomile',
    long: 'Calming passion fruit with soothing chamomile tea.',
    image: '/assets/products/product-29.png',
    category: 'Wellness',
    flavor: 'Passion Fruit',
    flavorColor: '#FBC02D',
    fruitIngredients: ['Passion Fruit'],
    sizes: [
      { size: '250ml', price: 279, calories: 110, protein: '2g', carbs: '26g', sugar: '21g', vitaminC: '50%', servingSize: '250ml' },
      { size: '500ml', price: 509, calories: 220, protein: '4g', carbs: '52g', sugar: '42g', vitaminC: '100%', servingSize: '500ml' },
      { size: '1L', price: 929, calories: 440, protein: '8g', carbs: '104g', sugar: '84g', vitaminC: '200%', servingSize: '1L' },
    ],
  },
  {
    id: 30,
    name: 'Cantaloupe Calm',
    price: 469,
    short: 'Cantaloupe & mint',
    long: 'Gentle cantaloupe juice with refreshing mint.',
    image: '/assets/products/product-30.png',
    category: 'Wellness',
    flavor: 'Cantaloupe',
    flavorColor: '#FFCCBC',
    fruitIngredients: ['Cantaloupe'],
    sizes: [
      { size: '250ml', price: 259, calories: 100, protein: '1g', carbs: '24g', sugar: '20g', vitaminC: '60%', servingSize: '250ml' },
      { size: '500ml', price: 469, calories: 200, protein: '2g', carbs: '48g', sugar: '40g', vitaminC: '120%', servingSize: '500ml' },
      { size: '1L', price: 859, calories: 400, protein: '4g', carbs: '96g', sugar: '80g', vitaminC: '240%', servingSize: '1L' },
    ],
  },
  {
    id: 31,
    name: 'Pear Perfection Tonic',
    price: 499,
    short: 'Asian pear & ginger',
    long: 'Crisp Asian pear with warming ginger root.',
    image: '/assets/products/product-31.png',
    category: 'Wellness',
    flavor: 'Pear',
    flavorColor: '#AED581',
    fruitIngredients: ['Pear'],
    sizes: [
      { size: '250ml', price: 269, calories: 115, protein: '1g', carbs: '28g', sugar: '23g', vitaminC: '40%', servingSize: '250ml' },
      { size: '500ml', price: 499, calories: 230, protein: '2g', carbs: '56g', sugar: '46g', vitaminC: '80%', servingSize: '500ml' },
      { size: '1L', price: 899, calories: 460, protein: '4g', carbs: '112g', sugar: '92g', vitaminC: '160%', servingSize: '1L' },
    ],
  },
  {
    id: 32,
    name: 'Tangerine Turmeric',
    price: 519,
    short: 'Tangerine, turmeric & black pepper',
    long: 'Sweet tangerine with anti-inflammatory turmeric boost.',
    image: '/assets/products/product-32.png',
    category: 'Wellness',
    flavor: 'Tangerine',
    flavorColor: '#FF9800',
    fruitIngredients: ['Tangerine', 'Orange'],
    sizes: [
      { size: '250ml', price: 289, calories: 120, protein: '2g', carbs: '28g', sugar: '24g', vitaminC: '65%', servingSize: '250ml' },
      { size: '500ml', price: 519, calories: 240, protein: '4g', carbs: '56g', sugar: '48g', vitaminC: '130%', servingSize: '500ml' },
      { size: '1L', price: 949, calories: 480, protein: '8g', carbs: '112g', sugar: '96g', vitaminC: '260%', servingSize: '1L' },
    ],
  },

  // ====== RESET MENU - CLEANSE PROGRAMS ======
  // Juice Cleanses (6)
  {
    id: 33,
    name: 'Green Detox Bundle',
    price: 2499,
    short: '6 bottles green juice cleanse',
    long: 'Complete 1-day green juice cleanse with kale, spinach, and cucumber.',
    image: '/assets/products/product-33.png',
    category: 'Juice Cleanses',
    flavor: 'Green',
    flavorColor: '#4CAF50',
    fruitIngredients: ['Apple', 'Kiwi', 'Lime'],
    sizes: [
      { size: '1-Day', price: 2499, calories: 600, protein: '12g', carbs: '140g', sugar: '100g', vitaminC: '400%', servingSize: '6 bottles' },
      { size: '3-Day', price: 6999, calories: 1800, protein: '36g', carbs: '420g', sugar: '300g', vitaminC: '1200%', servingSize: '18 bottles' },
      { size: '5-Day', price: 10999, calories: 3000, protein: '60g', carbs: '700g', sugar: '500g', vitaminC: '2000%', servingSize: '30 bottles' },
    ],
  },
  {
    id: 34,
    name: 'Rainbow Juice Pack',
    price: 2799,
    short: '6 bottles multi-fruit cleanse',
    long: 'Colorful variety pack with beetroot, carrot, orange, and greens.',
    image: '/assets/products/product-34.png',
    category: 'Juice Cleanses',
    flavor: 'Mixed',
    flavorColor: '#FF6B35',
    fruitIngredients: ['Orange', 'Apple', 'Watermelon', 'Grape', 'Kiwi'],
    sizes: [
      { size: '1-Day', price: 2799, calories: 720, protein: '15g', carbs: '165g', sugar: '120g', vitaminC: '500%', servingSize: '6 bottles' },
      { size: '3-Day', price: 7999, calories: 2160, protein: '45g', carbs: '495g', sugar: '360g', vitaminC: '1500%', servingSize: '18 bottles' },
      { size: '5-Day', price: 12499, calories: 3600, protein: '75g', carbs: '825g', sugar: '600g', vitaminC: '2500%', servingSize: '30 bottles' },
    ],
  },

  // Quick Reset (4)
  {
    id: 35,
    name: '3-Day Reset Kit',
    price: 4999,
    short: '18 bottles for 3-day cleanse',
    long: 'Gentle 3-day reset program with morning, noon, and evening juices.',
    image: '/assets/products/product-35.png',
    category: 'Quick Reset',
    flavor: 'Citrus',
    flavorColor: '#FFA726',
    fruitIngredients: ['Orange', 'Lemon', 'Lime', 'Grapefruit'],
    sizes: [
      { size: '3-Day', price: 4999, calories: 1800, protein: '30g', carbs: '420g', sugar: '320g', vitaminC: '900%', servingSize: '18 bottles' },
      { size: '5-Day', price: 7999, calories: 3000, protein: '50g', carbs: '700g', sugar: '530g', vitaminC: '1500%', servingSize: '30 bottles' },
      { size: '7-Day', price: 10999, calories: 4200, protein: '70g', carbs: '980g', sugar: '740g', vitaminC: '2100%', servingSize: '42 bottles' },
    ],
  },
  {
    id: 36,
    name: 'Weekend Refresh',
    price: 3999,
    short: '12 bottles weekend cleanse',
    long: '2-day weekend detox with energizing fruit and veggie blends.',
    image: '/assets/products/product-36.png',
    category: 'Quick Reset',
    flavor: 'Berry',
    flavorColor: '#E91E63',
    fruitIngredients: ['Strawberry', 'Blueberry', 'Raspberry', 'Blackberry'],
    sizes: [
      { size: '2-Day', price: 3999, calories: 1440, protein: '24g', carbs: '336g', sugar: '260g', vitaminC: '720%', servingSize: '12 bottles' },
      { size: '4-Day', price: 7499, calories: 2880, protein: '48g', carbs: '672g', sugar: '520g', vitaminC: '1440%', servingSize: '24 bottles' },
      { size: '7-Day', price: 12999, calories: 5040, protein: '84g', carbs: '1176g', sugar: '910g', vitaminC: '2520%', servingSize: '42 bottles' },
    ],
  },

  // Deep Cleanse (4)
  {
    id: 37,
    name: '5-Day Deep Cleanse',
    price: 7999,
    short: '30 bottles intensive program',
    long: 'Comprehensive 5-day cleanse with nutrient-dense superfood juices.',
    image: '/assets/products/product-37.png',
    category: 'Deep Cleanse',
    flavor: 'Superfood',
    flavorColor: '#673AB7',
    fruitIngredients: ['Acai', 'Pomegranate', 'Blueberry', 'Kiwi'],
    sizes: [
      { size: '5-Day', price: 7999, calories: 3000, protein: '60g', carbs: '720g', sugar: '550g', vitaminC: '1800%', servingSize: '30 bottles' },
      { size: '7-Day', price: 10999, calories: 4200, protein: '84g', carbs: '1008g', sugar: '770g', vitaminC: '2520%', servingSize: '42 bottles' },
      { size: '10-Day', price: 15499, calories: 6000, protein: '120g', carbs: '1440g', sugar: '1100g', vitaminC: '3600%', servingSize: '60 bottles' },
    ],
  },
  {
    id: 38,
    name: 'Total Body Reset',
    price: 8499,
    short: '30 bottles complete detox',
    long: '5-day total body cleanse with alkalizing greens and antioxidants.',
    image: '/assets/products/product-38.png',
    category: 'Deep Cleanse',
    flavor: 'Green',
    flavorColor: '#4CAF50',
    fruitIngredients: ['Apple', 'Kiwi', 'Lime', 'Pear'],
    sizes: [
      { size: '5-Day', price: 8499, calories: 2850, protein: '65g', carbs: '680g', sugar: '510g', vitaminC: '2000%', servingSize: '30 bottles' },
      { size: '7-Day', price: 11799, calories: 3990, protein: '91g', carbs: '952g', sugar: '714g', vitaminC: '2800%', servingSize: '42 bottles' },
      { size: '10-Day', price: 16499, calories: 5700, protein: '130g', carbs: '1360g', sugar: '1020g', vitaminC: '4000%', servingSize: '60 bottles' },
    ],
  },

  // Total Reboot (4)
  {
    id: 39,
    name: '7-Day Transformation',
    price: 11999,
    short: '42 bottles ultimate cleanse',
    long: 'Complete 7-day transformation with morning boost, lunch, and dinner juices.',
    image: '/assets/products/product-39.png',
    category: 'Total Reboot',
    flavor: 'Complete',
    flavorColor: '#2196F3',
    fruitIngredients: ['Apple', 'Orange', 'Watermelon', 'Grape', 'Mango', 'Pineapple'],
    sizes: [
      { size: '7-Day', price: 11999, calories: 4620, protein: '90g', carbs: '1100g', sugar: '840g', vitaminC: '2800%', servingSize: '42 bottles' },
      { size: '10-Day', price: 16999, calories: 6600, protein: '130g', carbs: '1570g', sugar: '1200g', vitaminC: '4000%', servingSize: '60 bottles' },
      { size: '14-Day', price: 23499, calories: 9240, protein: '180g', carbs: '2200g', sugar: '1680g', vitaminC: '5600%', servingSize: '84 bottles' },
    ],
  },
  {
    id: 40,
    name: 'Ultimate Detox Week',
    price: 12999,
    short: '49 bottles premium program',
    long: '7-day premium cleanse with probiotics and superfood boosters.',
    image: '/assets/products/product-40.png',
    category: 'Total Reboot',
    flavor: 'Premium',
    flavorColor: '#9C27B0',
    fruitIngredients: ['Pomegranate', 'Acai', 'Blueberry', 'Raspberry', 'Blackberry'],
    sizes: [
      { size: '7-Day', price: 12999, calories: 4900, protein: '98g', carbs: '1150g', sugar: '880g', vitaminC: '3200%', servingSize: '49 bottles' },
      { size: '10-Day', price: 18499, calories: 7000, protein: '140g', carbs: '1640g', sugar: '1260g', vitaminC: '4600%', servingSize: '70 bottles' },
      { size: '14-Day', price: 25999, calories: 9800, protein: '196g', carbs: '2300g', sugar: '1760g', vitaminC: '6400%', servingSize: '98 bottles' },
    ],
  },

  // ====== THRIVE MENU - MEAL PLANS ======
  // Beginner's Path (6)
  {
    id: 41,
    name: 'Starter Wellness Pack',
    price: 1999,
    short: 'Weekly juice + 2 meals',
    long: 'Perfect intro plan with 7 juices plus 2 healthy meal recipes.',
    image: '/assets/products/product-41.png',
    category: "Beginner's Path",
    flavor: 'Balanced',
    flavorColor: '#4CAF50',
    fruitIngredients: ['Apple', 'Orange', 'Banana'],
    sizes: [
      { size: '1-Week', price: 1999, calories: 3500, protein: '45g', carbs: '650g', sugar: '420g', vitaminC: '700%', servingSize: '7 juices + 2 meals' },
      { size: '2-Week', price: 3599, calories: 7000, protein: '90g', carbs: '1300g', sugar: '840g', vitaminC: '1400%', servingSize: '14 juices + 4 meals' },
      { size: '1-Month', price: 6999, calories: 14000, protein: '180g', carbs: '2600g', sugar: '1680g', vitaminC: '2800%', servingSize: '28 juices + 8 meals' },
    ],
  },
  {
    id: 42,
    name: 'Beginner Energy Bundle',
    price: 2299,
    short: 'Weekly smoothies + meal guide',
    long: 'Energizing smoothies with simple meal planning guide for beginners.',
    image: '/assets/products/product-42.png',
    category: "Beginner's Path",
    flavor: 'Energy',
    flavorColor: '#FFA726',
    fruitIngredients: ['Mango', 'Pineapple', 'Orange'],
    sizes: [
      { size: '1-Week', price: 2299, calories: 3850, protein: '55g', carbs: '720g', sugar: '460g', vitaminC: '800%', servingSize: '7 smoothies + guide' },
      { size: '2-Week', price: 4199, calories: 7700, protein: '110g', carbs: '1440g', sugar: '920g', vitaminC: '1600%', servingSize: '14 smoothies + guide' },
      { size: '1-Month', price: 7999, calories: 15400, protein: '220g', carbs: '2880g', sugar: '1840g', vitaminC: '3200%', servingSize: '28 smoothies + guide' },
    ],
  },

  // Premium Balance (6)
  {
    id: 43,
    name: 'Premium Nutrition Plan',
    price: 4999,
    short: 'Weekly juices + 5 gourmet meals',
    long: 'Curated juice selection with 5 chef-prepared organic meals.',
    image: '/assets/products/product-43.png',
    category: 'Premium Balance',
    flavor: 'Gourmet',
    flavorColor: '#9C27B0',
    fruitIngredients: ['Pomegranate', 'Fig', 'Grape', 'Apple'],
    sizes: [
      { size: '1-Week', price: 4999, calories: 7000, protein: '100g', carbs: '1200g', sugar: '700g', vitaminC: '1400%', servingSize: '7 juices + 5 meals' },
      { size: '2-Week', price: 9499, calories: 14000, protein: '200g', carbs: '2400g', sugar: '1400g', vitaminC: '2800%', servingSize: '14 juices + 10 meals' },
      { size: '1-Month', price: 17999, calories: 28000, protein: '400g', carbs: '4800g', sugar: '2800g', vitaminC: '5600%', servingSize: '28 juices + 20 meals' },
    ],
  },
  {
    id: 44,
    name: 'Balanced Living Package',
    price: 5499,
    short: 'Complete weekly meal plan',
    long: 'Full week of juices, smoothies, and balanced meals delivered fresh.',
    image: '/assets/products/product-44.png',
    category: 'Premium Balance',
    flavor: 'Complete',
    flavorColor: '#2196F3',
    fruitIngredients: ['Banana', 'Strawberry', 'Blueberry', 'Mango', 'Peach'],
    sizes: [
      { size: '1-Week', price: 5499, calories: 8400, protein: '120g', carbs: '1400g', sugar: '800g', vitaminC: '1600%', servingSize: 'Full week meals' },
      { size: '2-Week', price: 10499, calories: 16800, protein: '240g', carbs: '2800g', sugar: '1600g', vitaminC: '3200%', servingSize: '2 weeks meals' },
      { size: '1-Month', price: 19999, calories: 33600, protein: '480g', carbs: '5600g', sugar: '3200g', vitaminC: '6400%', servingSize: '4 weeks meals' },
    ],
  },

  // Elite Wellness (6)
  {
    id: 45,
    name: 'Elite Transformation',
    price: 9999,
    short: 'Premium juices + personal meals',
    long: 'Personalized juice blends with custom-prepared gourmet meals.',
    image: '/assets/products/product-45.png',
    category: 'Elite Wellness',
    flavor: 'Custom',
    flavorColor: '#FFD700',
    fruitIngredients: ['Apple', 'Orange', 'Pineapple', 'Mango', 'Watermelon', 'Grape'],
    sizes: [
      { size: '1-Week', price: 9999, calories: 10500, protein: '150g', carbs: '1800g', sugar: '1000g', vitaminC: '2000%', servingSize: 'Premium weekly plan' },
      { size: '2-Week', price: 18999, calories: 21000, protein: '300g', carbs: '3600g', sugar: '2000g', vitaminC: '4000%', servingSize: '2 weeks premium' },
      { size: '1-Month', price: 35999, calories: 42000, protein: '600g', carbs: '7200g', sugar: '4000g', vitaminC: '8000%', servingSize: '4 weeks premium' },
    ],
  },
  {
    id: 46,
    name: 'Luxury Wellness Plan',
    price: 11999,
    short: 'VIP weekly program',
    long: 'Ultimate wellness with superfood juices and 3-course daily meals.',
    image: '/assets/products/product-46.png',
    category: 'Elite Wellness',
    flavor: 'Luxury',
    flavorColor: '#E91E63',
    fruitIngredients: ['Pomegranate', 'Acai', 'Dragon Fruit', 'Passion Fruit', 'Guava'],
    sizes: [
      { size: '1-Week', price: 11999, calories: 12600, protein: '180g', carbs: '2100g', sugar: '1200g', vitaminC: '2400%', servingSize: 'VIP weekly plan' },
      { size: '2-Week', price: 22999, calories: 25200, protein: '360g', carbs: '4200g', sugar: '2400g', vitaminC: '4800%', servingSize: '2 weeks VIP' },
      { size: '1-Month', price: 43999, calories: 50400, protein: '720g', carbs: '8400g', sugar: '4800g', vitaminC: '9600%', servingSize: '4 weeks VIP' },
    ],
  },
];
