export const products = [
  // Detox (8)
  {
    id: 1,
    name: 'Apple Juice Cleanse',
    price: 499,
    short: 'Fresh apple & green goodness',
    long: 'Pure cold-pressed apple juice with a refreshing cleanse.',
    image: '/assets/products/apple.png',
    category: 'Detox',
  },
  {
    id: 2,
    name: 'Kiwi Fruit Kick',
    price: 549,
    short: 'Tangy kiwi & citrus burst',
    long: 'Energizing kiwifruit blend with a zesty citrus kick.',
    image: '/assets/products/kiwi.png',
    category: 'Detox',
  },
  {
    id: 3,
    name: 'Orange Sunrise Boost',
    price: 519,
    short: 'Fresh orange & vitamin C',
    long: 'Bright orange juice packed with natural vitamin C.',
    image: '/assets/products/orange.png',
    category: 'Detox',
  },
  {
    id: 4,
    name: 'Watermelon Wave',
    price: 449,
    short: 'Sweet watermelon refresh',
    long: 'Hydrating watermelon juice with a cool, sweet finish.',
    image: '/assets/products/watermelon.png',
    category: 'Detox',
  },
  {
    id: 5,
    name: 'Grape Glow Elixir',
    price: 459,
    short: 'Red grape & antioxidants',
    long: 'Rich red grape juice loaded with antioxidants.',
    image: '/assets/products/grape.png',
    category: 'Detox',
  },
  {
    id: 6,
    name: 'Pineapple Paradise',
    price: 469,
    short: 'Tropical pineapple delight',
    long: 'Sweet tropical pineapple juice with island vibes.',
    image: '/assets/products/pineapple.png',
    category: 'Detox',
  },
  {
    id: 7,
    name: 'Mango Bliss',
    price: 509,
    short: 'Ripe mango perfection',
    long: 'Smooth, velvety mango juice with tropical sweetness.',
    image: '/assets/products/mango.png',
    category: 'Detox',
  },
  {
    id: 8,
    name: 'Strawberry Fields',
    price: 499,
    short: 'Fresh strawberry crush',
    long: 'Sweet, fragrant strawberry juice with berry richness.',
    image: '/assets/products/strawberry.png',
    category: 'Detox',
  },

  // Smoothies (8)
  {
    id: 9,
    name: 'Blueberry Dream',
    price: 539,
    short: 'Blueberry & Greek yogurt',
    long: 'Creamy blueberry smoothie with protein-rich Greek yogurt.',
    image: '/assets/products/blueberry.png',
    category: 'Smoothies',
  },
  {
    id: 10,
    name: 'Banana Split Smoothie',
    price: 579,
    short: 'Banana, honey & almond',
    long: 'Classic banana smoothie with honey and almond milk.',
    image: '/assets/products/banana.png',
    category: 'Smoothies',
  },
  {
    id: 11,
    name: 'Peach Perfection',
    price: 659,
    short: 'Peach, vanilla & oat milk',
    long: 'Velvety peach smoothie with vanilla and creamy oats.',
    image: '/assets/products/peach.png',
    category: 'Smoothies',
  },
  {
    id: 12,
    name: 'Cherry Charm',
    price: 579,
    short: 'Sweet cherry & yogurt',
    long: 'Rich cherry smoothie with a tangy yogurt twist.',
    image: '/assets/products/product-12.png',
    category: 'Smoothies',
  },
  {
    id: 13,
    name: 'Papaya Power Blend',
    price: 559,
    short: 'Papaya, lime & coconut',
    long: 'Tropical papaya smoothie with lime and coconut cream.',
    image: '/assets/products/product-13.png',
    category: 'Smoothies',
  },
  {
    id: 14,
    name: 'Guava Goodness',
    price: 549,
    short: 'Pink guava & passion fruit',
    long: 'Exotic guava smoothie with passion fruit tang.',
    image: '/assets/products/product-14.png',
    category: 'Smoothies',
  },
  {
    id: 15,
    name: 'Lychee Love',
    price: 559,
    short: 'Lychee & rose water',
    long: 'Delicate lychee smoothie with a hint of rose.',
    image: '/assets/products/product-15.png',
    category: 'Smoothies',
  },
  {
    id: 16,
    name: 'Dragon Fruit Delight',
    price: 569,
    short: 'Dragon fruit & chia seeds',
    long: 'Vibrant dragon fruit smoothie with omega-rich chia.',
    image: '/assets/products/product-16.png',
    category: 'Smoothies',
  },

  // Protein (8)
  {
    id: 17,
    name: 'Raspberry Protein Punch',
    price: 619,
    short: 'Raspberry, whey & almond',
    long: 'Tart raspberry with smooth whey protein and almond milk.',
    image: '/assets/products/product-17.png',
    category: 'Protein',
  },
  {
    id: 18,
    name: 'Blackberry Muscle Mix',
    price: 629,
    short: 'Blackberry, oats & protein',
    long: 'Bold blackberry with hearty oats and whey protein.',
    image: '/assets/products/product-18.png',
    category: 'Protein',
  },
  {
    id: 19,
    name: 'Apricot Energy Shake',
    price: 639,
    short: 'Apricot, banana & whey',
    long: 'Sweet apricot protein shake with banana creaminess.',
    image: '/assets/products/product-19.png',
    category: 'Protein',
  },
  {
    id: 20,
    name: 'Pomegranate Power',
    price: 649,
    short: 'Pomegranate, berries & protein',
    long: 'Antioxidant-rich pomegranate with mixed berries and whey.',
    image: '/assets/products/product-20.png',
    category: 'Protein',
  },
  {
    id: 21,
    name: 'Coconut Protein Paradise',
    price: 609,
    short: 'Coconut milk, pineapple & whey',
    long: 'Tropical coconut protein with sweet pineapple chunks.',
    image: '/assets/products/product-21.png',
    category: 'Protein',
  },
  {
    id: 22,
    name: 'Fig Fitness Fuel',
    price: 639,
    short: 'Fig, date & pea protein',
    long: 'Natural fig sweetness with dates and plant protein.',
    image: '/assets/products/product-22.png',
    category: 'Protein',
  },
  {
    id: 23,
    name: 'Plum Performance',
    price: 629,
    short: 'Plum, vanilla & whey',
    long: 'Juicy plum protein shake with smooth vanilla notes.',
    image: '/assets/products/product-23.png',
    category: 'Protein',
  },
  {
    id: 24,
    name: 'Avocado Green Protein',
    price: 639,
    short: 'Avocado, spinach & hemp protein',
    long: 'Creamy avocado with greens and plant-based hemp protein.',
    image: '/assets/products/product-24.png',
    category: 'Protein',
  },

  // Wellness (8)
  {
    id: 25,
    name: 'Grapefruit Glow',
    price: 449,
    short: 'Pink grapefruit & honey',
    long: 'Tangy pink grapefruit with a touch of natural honey.',
    image: '/assets/products/product-25.png',
    category: 'Wellness',
  },
  {
    id: 26,
    name: 'Lemon Lime Vitality',
    price: 479,
    short: 'Lemon, lime & mint',
    long: 'Refreshing citrus duo with cooling mint leaves.',
    image: '/assets/products/product-26.png',
    category: 'Wellness',
  },
  {
    id: 27,
    name: 'Cranberry Cleanse',
    price: 399,
    short: 'Cranberry & hibiscus',
    long: 'Tart cranberry juice with floral hibiscus notes.',
    image: '/assets/products/product-27.png',
    category: 'Wellness',
  },
  {
    id: 28,
    name: 'Acai Berry Immunity',
    price: 489,
    short: 'Acai, blueberry & elderberry',
    long: 'Superfood acai blend with immune-boosting elderberry.',
    image: '/assets/products/product-28.png',
    category: 'Wellness',
  },
  {
    id: 29,
    name: 'Passion Fruit Zen',
    price: 509,
    short: 'Passion fruit & chamomile',
    long: 'Calming passion fruit with soothing chamomile tea.',
    image: '/assets/products/product-29.png',
    category: 'Wellness',
  },
  {
    id: 30,
    name: 'Cantaloupe Calm',
    price: 469,
    short: 'Cantaloupe & mint',
    long: 'Gentle cantaloupe juice with refreshing mint.',
    image: '/assets/products/product-30.png',
    category: 'Wellness',
  },
  {
    id: 31,
    name: 'Pear Perfection Tonic',
    price: 499,
    short: 'Asian pear & ginger',
    long: 'Crisp Asian pear with warming ginger root.',
    image: '/assets/products/product-31.png',
    category: 'Wellness',
  },
  {
    id: 32,
    name: 'Tangerine Turmeric',
    price: 519,
    short: 'Tangerine, turmeric & black pepper',
    long: 'Sweet tangerine with anti-inflammatory turmeric boost.',
    image: '/assets/products/product-32.png',
    category: 'Wellness',
  },
];